# Generated by Django 4.1.7 on 2023-03-14 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('constituency_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('voter_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.candidates')),
                ('constituency_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.regions')),
            ],
        ),
        migrations.AddField(
            model_name='candidates',
            name='constituency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.regions'),
        ),
    ]
