# Generated by Django 4.1.7 on 2023-03-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voters',
            name='constituency_id',
        ),
        migrations.RemoveField(
            model_name='candidates',
            name='constituency_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='constituency_id',
        ),
        migrations.AddField(
            model_name='vote',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Regions',
        ),
        migrations.DeleteModel(
            name='Voters',
        ),
    ]
